### PR TITLE
Add support for defaultTabIndex props in tab component because by default it select first tab as active tab

### PR DESCRIPTION
**Pull request by vpsk**
Add support for defaultTabIndex props in tab component because by default it select first tab as active tab

### CODE REVIEW

**Review by Sreejit7 — APPROVED** [review]

**Comment by sujan-s** [comment]
@vpsk Here’s an idea—

```
tabs={[
    {
        key: "tab1",
        label: "Tab 1",
        content: Tab1Content(),
    },
    {
        key: "tab2",
        label: "Tab 2",
        content: Tab2Content(),
        isActive <—— <—— 
    }
}
```

What say we pass an `isActive` attribute to whatever tab you want activated by default?

**Comment by vpsk** [comment]
@sujan-s default active Index is for only the first render and it should be independent of the tab details array.  

isActive in tab object will make sense to get information about the currently active tab.

**Review by ghostwriternr — DISMISSED** [review]

**Comment by sujan-s** [comment]
@vpsk Understood. Makes sense. Here’s another thing to think about—`defaultTabIndex` is very dev-centric, and against the general Fictoan ideology. Can we do something like `defaultActiveTab="tab1"`, which would be the value of the key in the `tabs` object.

That way, it’s plain English and self-explanatory.

Also, can you update the CHANGELOG and the version too, please? Once we merge to master, it’ll update the npm package too.

**Comment by vpsk** [comment]
@sujan-s update the naming of prop and active tab based on key.

**Review by sujan-s — APPROVED** [review]

**Pull request merged**
